#!/bin/bash

# Seed Script for Image Guess Duel
# This script provides instructions for pre-uploading sample images

echo "======================================"
echo "Image Guess Duel - Image Seed Guide"
echo "======================================"
echo ""
echo "To pre-load images for your party:"
echo ""
echo "OPTION 1: Via Host UI (Recommended)"
echo "-----------------------------------"
echo "1. Run the app: npm run dev"
echo "2. Sign in as Host (check 'I'm the Host')"
echo "3. Start a match with any two players"
echo "4. On the Host Panel, click 'Upload New Image'"
echo "5. Select your image files"
echo "6. Repeat for all images you want to upload"
echo "7. Cancel the round when done"
echo ""
echo "OPTION 2: Via Firebase Console"
echo "-------------------------------"
echo "1. Go to Firebase Console > Storage"
echo "2. Create a folder: images/host_uploads/"
echo "3. Upload your images to that folder"
echo "4. Go to Firestore Database"
echo "5. Add documents to 'images' collection with:"
echo "   - url: [Download URL from Storage]"
echo "   - uploadedBy: [Your host user ID]"
echo "   - uploadedAt: [Current timestamp in ms]"
echo "   - name: [Filename]"
echo ""
echo "SAMPLE IMAGES FOR YOUR PARTY:"
echo "-----------------------------"
echo "Good categories for Christmas party:"
echo "- Famous landmarks (Eiffel Tower, Big Ben, etc.)"
echo "- Movies (Star Wars, Harry Potter, etc.)"
echo "- Animals (Cat, Dog, Elephant, etc.)"
echo "- Food (Pizza, Burger, Sushi, etc.)"
echo "- Christmas themes (Santa, Reindeer, Snowman, etc.)"
echo "- Sports (Football, Basketball, Tennis, etc.)"
echo ""
echo "TIP: Keep answers simple and unambiguous!"
echo "======================================"
